**NumPy -> Numerical Python**

`NumPy is a Library which is used to work with dimensionality of the data : `

In [ ]:
import numpy as np
len(dir(np))

532

- `array `
- `arange `
- `ndim `
- `size `
- `shape`
- `reshape `
- `reshape (-1,1) and reshape(1,-1)`
- `zeros `
- `ones `
- `full `
- `eye `
- `ravel `
- `concatinate `
- `Transpose `
- `random -> randint`
- `random -> randn `
- `random -> rand`
- `random -> random `
- `sum `
- `max `
- `min `
- `axis = 1`
- `axis = 0`
- `argmax `
- `argmin `


In [ ]:
# array = which is used to create data in the form of dimension
# 1D

a = np.array([10,20,30,40,50]) # 1D

print(a) # calling from memory

print(type(a)) # checking dtype

print(a.ndim) # used to check number of dims

print(a.shape) # check rows and columns -> (row,column)

print(a.size) # total number of values

[10 20 30 40 50]
<class 'numpy.ndarray'>
1
(5,)
5


In [ ]:
print(a[2])

30


In [ ]:
# 2D

a = np.array([ [1,4,9] , [10,7,3] , [11,8,14]   ] )

print(a) # calling from memory

print(type(a)) # checking dtype

print(a.ndim) # used to check number of dims

print(a.shape) # check rows and columns -> (row,column)

print(a.size) # total number of values

[[ 1  4  9]
 [10  7  3]
 [11  8 14]]
<class 'numpy.ndarray'>
2
(3, 3)
9


In [ ]:
print(a[1][2])

3


In [ ]:
# arange = arange function will take starting_point and ending_point:
# arange function will give outcome in 1D format


a = np.arange(11,17)

print(a)

print(a.ndim)

[11 12 13 14 15 16]
1


In [ ]:
# 1D to 2D

a = np.arange(1,61)

print(a)
print(a.ndim)

b = a.reshape(10,6)

print(b)
print(b.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]
1
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]
2


In [ ]:
a = np.arange(1,61).reshape(10,6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]


In [ ]:
print(a[4][2])

27


In [ ]:
a = np.arange(1,61).reshape(2,5,6)
print(a)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [13 14 15 16 17 18]
  [19 20 21 22 23 24]
  [25 26 27 28 29 30]]

 [[31 32 33 34 35 36]
  [37 38 39 40 41 42]
  [43 44 45 46 47 48]
  [49 50 51 52 53 54]
  [55 56 57 58 59 60]]]


In [ ]:
print(a[1][2][3])

46


In [ ]:
print(a[2][1][3])

34


In [ ]:
print(a[4][0][3])

52


In [ ]:
# reshape(-1,1)

a = np.array([10,20,50,90,11,5])
print(a)
print(a.ndim)

b = a.reshape(-1,1)
print(b)
print(b.ndim)
print(b.shape)

[10 20 50 90 11  5]
1
[[10]
 [20]
 [50]
 [90]
 [11]
 [ 5]]
2
(6, 1)


In [ ]:
# reshape(1,-1)

a = np.array([10,20,50,90,11,5])
print(a)
print(a.ndim)

b = a.reshape(1,-1)
print(b)
print(b.ndim)
print(b.shape)

[10 20 50 90 11  5]
1
[[10 20 50 90 11  5]]
2
(1, 6)


In [ ]:
# ravel -> any dim will be converted back to 1D

a = np.array([ [1,4,9] , [10,7,3] , [11,8,14]   ] )
print(a)
print(a.ndim)

b = a.ravel()
print(b)
print(b.ndim)

[[ 1  4  9]
 [10  7  3]
 [11  8 14]]
2
[ 1  4  9 10  7  3 11  8 14]
1


In [ ]:
# transpose

a = np.array([ [1,4,9] , [10,7,3] , [11,8,14]   ] )

print(a)

b = a.T

print(b)

[[ 1  4  9]
 [10  7  3]
 [11  8 14]]
[[ 1 10 11]
 [ 4  7  8]
 [ 9  3 14]]


In [ ]:
# zeros
# default data type for numpy is float64

a = np.zeros((5,4))
print(a)
print(a.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


In [ ]:
# zeros
# default data type for numpy is float64

a = np.zeros((5,4) , dtype = np.int64)
print(a)
print(a.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int64


In [ ]:
# ones

a = np.ones((5,4),dtype=np.int64)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
# full

a = np.full((5,4) , 9)
print(a)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [ ]:
# eye
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# random -> randint

a = np.random.randint(10,50,5)

print(a)

[32 30 49 49 44]


In [ ]:
# random -> rand -> 0 to 1

a = np.random.rand(5,4)

print(a)

[[0.77840336 0.88544713 0.43979522 0.15343706]
 [0.91224138 0.96022868 0.99857721 0.25131751]
 [0.74349543 0.28083006 0.72833537 0.80394592]
 [0.31167783 0.66710393 0.28035887 0.65675089]
 [0.40792038 0.56629141 0.27585446 0.17962304]]


In [ ]:
# random -> randn -> -1 t0 1

a = np.random.randn(5,4)

print(a)

[[ 0.44459046 -0.58033375 -0.51122888  0.42063736]
 [-1.33983551 -0.76156302  0.78336999  0.22388738]
 [ 0.7308153   1.30943012 -1.91216869  1.3552067 ]
 [-1.13904309  0.31530085  1.9987937   1.56237519]
 [ 0.25603051  0.21852238 -0.25787217 -1.71742658]]


In [ ]:
# random -> random -> 0 to 1

a = np.random.random((5,4))

print(a)

[[0.34771928 0.93363078 0.47681947 0.87182297]
 [0.29864088 0.04569041 0.67271337 0.77803637]
 [0.71248905 0.20231312 0.48765577 0.21812807]
 [0.3095682  0.47486372 0.62964718 0.53628756]
 [0.64537033 0.00801866 0.72878297 0.26578415]]


In [ ]:
# concatination:

a = np.array([ [1,4,9] , [10,7,3] , [11,8,14]   ] )
b = np.array([ [10,5,19], [11,17,2] , [100,4,1] ] )

c = np.concatenate((a,b))
print(c)

[[  1   4   9]
 [ 10   7   3]
 [ 11   8  14]
 [ 10   5  19]
 [ 11  17   2]
 [100   4   1]]


In [ ]:
a = np.array([ [1,4,9] , [10,7,3] , [11,8,14]   ] )
b = np.array([ [10,5,19], [11,17,2] , [100,4,1] ] )

print(a + b)

[[ 11   9  28]
 [ 21  24   5]
 [111  12  15]]


In [ ]:
a = np.array([ [1,4,9] , [10,7,3] , [11,8,14]   ] )

print(np.sum(a))

67


In [ ]:
# axis = 1 -> row
# axis = 0 -> column

In [ ]:
a = np.array([ [1,4,9] , [10,7,3] , [11,8,14]   ] )

print(np.sum(a , axis = 1))

[14 20 33]


In [ ]:
a = np.array([ [1,4,9] , [10,7,3] , [11,8,14]   ] )

print(np.sum(a , axis = 0))

[22 19 26]


In [ ]:
a = np.array([ [1,4,9] , [10,7,3] , [11,8,14]   ] )

print(np.max(a))

14


In [ ]:
a = np.array([ [1,4,9] , [10,7,3] , [11,8,14]   ] )

print(np.max(a , axis=1))

[ 9 10 14]


In [ ]:
a = np.array([ [1,4,9] , [10,7,3] , [11,8,14]   ] )

print(np.max(a , axis=0))

[11  8 14]


In [ ]:
a = np.array([ [1,4,9] , [10,7,3] , [11,8,14]   ] )

print(np.min(a , axis=1))

[1 3 8]


In [ ]:
# argmax and argmin

a = np.array([ [1,4,9] , [10,7,3] , [11,8,14]   ] )

print(np.max(a))

14


In [ ]:
# argmax and argmin

a = np.array([ [1,4,9] , [10,7,3] , [11,8,14]   ] )

print(np.min(a))

1


In [ ]:
# argmax and argmin

a = np.array([ [1,4,9] , [10,7,3] , [11,8,14]   ] )

print(np.argmax(a))

8


In [ ]:
# argmax and argmin

a = np.array([ [1,4,9] , [10,7,3] , [11,8,14]   ] )

print(np.argmin(a))

0


In [ ]:
# argmax and argmin

a = np.array([ [1,4,9] , [10,7,3] , [11,8,14]   ] )

print(np.max(a , axis = 1))

[ 9 10 14]


In [ ]:
# argmax and argmin

a = np.array([ [1,4,9] , [10,7,3] , [11,8,14]   ] )

print(np.argmax(a , axis = 1))

[2 0 2]


In [ ]:
# argmax and argmin

a = np.array([ [1,4,9] , [10,7,3] , [11,8,14]   ] )

print(np.argmin(a , axis = 0))

[0 0 1]


In [ ]:
a = np.array([ [1,4,9] , [10,7,3] , [11,8,14]   ] )
b = np.array([ [10,5,19], [11,17,2] , [100,4,1] ] )

print(np.add(a,b))

[[ 11   9  28]
 [ 21  24   5]
 [111  12  15]]


In [ ]:
a = np.array([ [1,4,9] , [10,7,3] , [11,8,14]   ] )
b = np.array([ [10,5,19], [11,17,2] , [100,4,1] ] )

print(np.subtract(a,b))

[[ -9  -1 -10]
 [ -1 -10   1]
 [-89   4  13]]


In [ ]:
# matmul:

a = np.array([ [1,4,7] , [3,8,1] ])
b = np.array([ [1] , [2] , [3]])

print(np.matmul(a,b))

[[30]
 [22]]


In [ ]:
# matmul:

a = np.array([ [1,4,7] , [3,8,1] ])
b = np.array([ [1 , 10] , [11,15] ])

print(np.matmul(a,b))

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [ ]:
a = np.array([ [1,4,9] , [10,7,3] , [11,8,14]   ] )

for i in a:
  print(i)

[1 4 9]
[10  7  3]
[11  8 14]


In [ ]:
a = np.array([ [1,4,9] , [10,7,3] , [11,8,14]   ] )
c = []

for i in a:
  c.append(sum(i))

print(c)

[np.int64(14), np.int64(20), np.int64(33)]


In [ ]:
a = np.array([ [1,4,9] , [10,7,3] , [11,8,14]   ] )
b = a[0].tolist()
print(type(b))
print(b)

<class 'list'>
[1, 4, 9]


In [ ]:
a = np.array([ [1,4,9] , [10,7,3] , [11,8,14]   ] )
c = []

for i in a:
  f = 0
  for j in i.tolist():
    f = f + j
  c.append(f)


print(c)

[14, 20, 33]


In [1]:
# 5 challenging Interview questions on NumPy:

In [9]:
import numpy as np
a = np.array([[1,4,9] , [3,7,2] , [10,18,25]])
print(a.shape[0])
f = []
c = 0
for i in range(a.shape[0]):
  f.append(a[i][c])
  c = c + 1

print(f)

3
[np.int64(1), np.int64(7), np.int64(25)]


In [11]:
import numpy as np
a = np.array([[1,4,9] , [3,7,2] , [10,18,25]])
print(a.shape[0])
f = []
c = 0
for i in range(a.shape[0]):
  c = c - 1
  f.append(a[i][c])


print(f)

3
[np.int64(9), np.int64(7), np.int64(10)]


In [13]:
a = [10,22,12]
c = 0

for i in a:
  c = c + i

print(c)

44


In [16]:
import numpy as np
a = np.array([[1,4,9] , [3,7,2] , [10,18,25]])
d = []
for i in a:
  c = 0
  for j in i:
    c = c + j
  d.append(c)

p = 0
for k in d:
  p = p + k

print(p)

79


In [26]:
import numpy as np
a = np.array([[1,4,9] , [3,7,2] , [10,18,25]])

f_c = []
s_c = []
t_c = []


for i in a:
  f_c.append(i[0])
  s_c.append(i[1])
  t_c.append(i[2])


s_f_c = 0
s_s_c = 0
s_t_c = 0

for j in range(3):
  s_f_c = s_f_c + f_c[j]
  s_s_c = s_s_c + s_c[j]
  s_t_c = s_t_c + t_c[j]

print(s_f_c + s_s_c + s_t_c)

79


In [28]:
import numpy as np
a = np.array([[1,4,9] , [3,7,2] , [10,18,25]])

c = 0

for i in a:
  for j in i:
    if j % 2 == 0:
      c = c + j
print(c)

34
